### ISSUE TITLE
Postcss removed

### ISSUE THREAD

**Issue by codytooker** [nativescript-vue/vue-cli-plugin-nativescript-vue#14]
It seems like this plugin removes the ability to use postcss is there a reason for this?

**Comment by jawa-the-hutt** [comment]
It was breaking things in the original development cycles spent getting this plugin going. I've added a commit to the dev branch that will hopefully address this.

Create a new vue project as normal and then install and invoke like this to test this out:
`npm install git+https://github.com/nativescript-vue/vue-cli-plugin-nativescript-vue/tree/dev`
`npm invoke vue-cli-plugin-nativescript-vue`

Once we have some validation it doesn't break things, i'll push to master and update the npm package.

**Comment by jawa-the-hutt** [comment]
Sorry, wrong install link for the `dev` branch.  here's the correct one:
`npm install git+https://github.com/nativescript-vue/vue-cli-plugin-nativescript-vue.git#dev`

**Comment by jawa-the-hutt** [comment]
Should be addressed in #19
