### ISSUE TITLE
default project is not compatible with NativeScript CLI 6.0

### ISSUE THREAD

**Issue by fei4xu** [nativescript-vue/vue-cli-plugin-nativescript-vue#30]
when I follow the readme and create a vue project then add this plugin, the default project is not compatible with NativeScript CLI 6.0, I have to run `tns migrate` before I can run `npm run debug:android`.

I think the default template should be updated to be compatible with latest 6.0 version.

**Comment by fei4xu** [comment]
> Updating 'tns-core-modules' to compatible version '6.0.1'
> Updating 'nativescript-dev-webpack' to compatible version '1.0.1'
> Updating Android platform to version '6.0.0'.
> Updating iOS platform to version '6.0.1'.

**Comment by jawa-the-hutt** [comment]
I've just released 0.2.0 of the plugin to npm. This includes NS 6.1.0 and NS-Vue 2.4.0.  Try it again and let me know if this addresses things.
