### ISSUE TITLE
Webpack - vuetify

### ISSUE THREAD

**Issue by acamenhas** [nativescript-vue/vue-cli-plugin-nativescript-vue#41]
Hi all,

I've vuetify installed in my dual app.
There is any way to configure webpack to "not load" vuetify on the native env?

Thanks!

**Comment by MaximeBoubel** [comment]
Hi @acamenhas , any success with that issue? 
I tried to modify the vue.config.js file to add some config to webpack but with no success.

**Comment by thond1st** [comment]
Hi @acamenhas and @MaximeBoubel ,
Have you found any solution?
Thanks
